// This file was generated by Dashcode from Apple Computer, Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
function setupParts() {
    if (setupParts.called) return;
    setupParts.called = true;
    CreateInfoButton('info', { frontID: 'front', foregroundStyle: 'white', backgroundStyle: 'black', onclick: 'showBack' });
    CreateGlassButton('done', { text: 'Done', onclick: 'showFront' });
    CreateText('hoursLabel', { text: 'hoursLabel' });
    CreateText('infoText', { text: 'infoText' });
    CreateText('loadingIndicator', { text: 'loadingMessage' });
    CreateText('errorMessage', { text: 'errorDataLoad' });
    CreateText('day0', { text: 'X' });
    CreateText('day1', { text: 'X' });
    CreateText('day3', { text: 'X' });
    CreateText('day2', { text: 'X' });
    CreateText('day5', { text: 'X' });
    CreateText('day4', { text: 'X' });
    CreateText('day6', { text: 'X' });
    CreateOvalShape('todayBg', {  });
}
window.addEventListener('load', setupParts, false);
