/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "errorDataLoad": "An error occured when loading time entries from the database, a new attempt will be made in a minute or so.",
    "errorNoBillings": "The Billings database could not be found. This widget requires that you have Billings 2.0 installed.",
    "forever": "Forever",
    "friday": "friday",
    "hoursLabel": "%hours% hours",
    "infoText": "%version% by Theo Hultberg / Iconara.",
    "infoUrl": "http://developer.iconara.net",
    "lastYear": "Last year",
    "loadingMessage": "Loading...",
    "monday": "monday",
    "newVersionAvailable": "There is a new version available, click here to download →",
    "oneMonth": "One month",
    "reportError": "If this is a persistent error, or you belive it to be a bug, please click here to report it. The relevant details will automatically be included.",
    "saturday": "saturday",
    "sixMonths": "Six months",
    "sunday": "sunday",
    "thursday": "thursday",
    "tuesday": "tuesday",
    "twoMonths": "Two months",
    "wednesday": "wednesday"
};

